// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtoM.Server;

namespace MtoM.Server.Migrations
{
    [DbContext(typeof(DBcon))]
    [Migration("20201208171413_blabla2")]
    partial class blabla2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MtoM.Server.Artikal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Artikli");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Naziv = "Bla"
                        },
                        new
                        {
                            ID = -2,
                            Naziv = "A2"
                        },
                        new
                        {
                            ID = -3,
                            Naziv = "A3"
                        });
                });

            modelBuilder.Entity("MtoM.Server.Racun", b =>
                {
                    b.Property<int>("RbR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("RbR");

                    b.ToTable("Racuni");

                    b.HasData(
                        new
                        {
                            RbR = -1,
                            DatumIzdavanja = new DateTime(2020, 12, 8, 18, 14, 12, 262, DateTimeKind.Local).AddTicks(4302)
                        },
                        new
                        {
                            RbR = -2,
                            DatumIzdavanja = new DateTime(2020, 12, 1, 18, 14, 12, 269, DateTimeKind.Local).AddTicks(449)
                        },
                        new
                        {
                            RbR = -3,
                            DatumIzdavanja = new DateTime(2020, 12, 12, 18, 14, 12, 269, DateTimeKind.Local).AddTicks(580)
                        });
                });

            modelBuilder.Entity("MtoM.Server.Racun_Artikal", b =>
                {
                    b.Property<int>("A_FK")
                        .HasColumnType("int");

                    b.Property<int>("R_FK")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.HasKey("A_FK", "R_FK");

                    b.HasIndex("R_FK");

                    b.ToTable("RAs");

                    b.HasData(
                        new
                        {
                            A_FK = -2,
                            R_FK = -1,
                            Kolicina = 5
                        },
                        new
                        {
                            A_FK = -1,
                            R_FK = -2,
                            Kolicina = 2
                        },
                        new
                        {
                            A_FK = -3,
                            R_FK = -2,
                            Kolicina = 7
                        },
                        new
                        {
                            A_FK = -1,
                            R_FK = -3,
                            Kolicina = 1
                        });
                });

            modelBuilder.Entity("MtoM.Shared.Nesto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VremenaZaBazu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Nestos");
                });

            modelBuilder.Entity("MtoM.Shared.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tim_FK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Tim_FK");

                    b.ToTable("Radniks");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Naziv = "Pera",
                            Tim_FK = -1
                        },
                        new
                        {
                            ID = -2,
                            Naziv = "Neko",
                            Tim_FK = -1
                        });
                });

            modelBuilder.Entity("MtoM.Shared.Tim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tims");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Naziv = "A"
                        });
                });

            modelBuilder.Entity("MtoM.Server.Racun_Artikal", b =>
                {
                    b.HasOne("MtoM.Server.Artikal", "Artikal")
                        .WithMany("RAs")
                        .HasForeignKey("A_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtoM.Server.Racun", "Racun")
                        .WithMany("RAs")
                        .HasForeignKey("R_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Racun");
                });

            modelBuilder.Entity("MtoM.Shared.Radnik", b =>
                {
                    b.HasOne("MtoM.Shared.Tim", "Tim")
                        .WithMany("Radniks")
                        .HasForeignKey("Tim_FK");

                    b.Navigation("Tim");
                });

            modelBuilder.Entity("MtoM.Server.Artikal", b =>
                {
                    b.Navigation("RAs");
                });

            modelBuilder.Entity("MtoM.Server.Racun", b =>
                {
                    b.Navigation("RAs");
                });

            modelBuilder.Entity("MtoM.Shared.Tim", b =>
                {
                    b.Navigation("Radniks");
                });
#pragma warning restore 612, 618
        }
    }
}
