// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtoM.Server;

namespace MtoM.Server.Migrations
{
    [DbContext(typeof(DBcon))]
    partial class DBconModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MtoM.Shared.Artikal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Artikli");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Naziv = "Bla"
                        },
                        new
                        {
                            ID = -2,
                            Naziv = "A2"
                        },
                        new
                        {
                            ID = -3,
                            Naziv = "A3"
                        });
                });

            modelBuilder.Entity("MtoM.Shared.Racun", b =>
                {
                    b.Property<int>("RbR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("RbR");

                    b.ToTable("Racuni");

                    b.HasData(
                        new
                        {
                            RbR = -1,
                            DatumIzdavanja = new DateTime(2020, 12, 7, 20, 9, 7, 835, DateTimeKind.Local).AddTicks(8199)
                        },
                        new
                        {
                            RbR = -2,
                            DatumIzdavanja = new DateTime(2020, 11, 30, 20, 9, 7, 840, DateTimeKind.Local).AddTicks(1918)
                        },
                        new
                        {
                            RbR = -3,
                            DatumIzdavanja = new DateTime(2020, 12, 11, 20, 9, 7, 840, DateTimeKind.Local).AddTicks(2090)
                        });
                });

            modelBuilder.Entity("MtoM.Shared.Racun_Artikal", b =>
                {
                    b.Property<int>("A_FK")
                        .HasColumnType("int");

                    b.Property<int>("R_FK")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.HasKey("A_FK", "R_FK");

                    b.HasIndex("R_FK");

                    b.ToTable("RAs");

                    b.HasData(
                        new
                        {
                            A_FK = -2,
                            R_FK = -1,
                            Kolicina = 5
                        },
                        new
                        {
                            A_FK = -1,
                            R_FK = -2,
                            Kolicina = 2
                        },
                        new
                        {
                            A_FK = -3,
                            R_FK = -2,
                            Kolicina = 7
                        },
                        new
                        {
                            A_FK = -1,
                            R_FK = -3,
                            Kolicina = 1
                        });
                });

            modelBuilder.Entity("MtoM.Shared.Racun_Artikal", b =>
                {
                    b.HasOne("MtoM.Shared.Artikal", "Artikal")
                        .WithMany("RAs")
                        .HasForeignKey("A_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtoM.Shared.Racun", "Racun")
                        .WithMany("RAs")
                        .HasForeignKey("R_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Racun");
                });

            modelBuilder.Entity("MtoM.Shared.Artikal", b =>
                {
                    b.Navigation("RAs");
                });

            modelBuilder.Entity("MtoM.Shared.Racun", b =>
                {
                    b.Navigation("RAs");
                });
#pragma warning restore 612, 618
        }
    }
}
